<?
$PERM["registratsiya-spetsialista"]["7"]="X";
$PERM["registratsiya-spetsialista"]["*"]="D";
$PERM["bitrix"]["9"]="R";
$PERM["/"]["9"]="W";
$PERM["/"]["*"]="R";
$PERM["desktop_app"]["*"]="D";
$PERM["updateAllPricestoBase2.php"]["*"]="D";
$PERM["updateAllPricestoBase1.php"]["*"]="D";
$PERM["updateAllPricestoBase.php"]["*"]="D";
$PERM["personal"]["8"]="W";
$PERM["catalog"]["8"]="W";
$PERM["news"]["8"]="W";
$PERM["about"]["8"]="W";
$PERM["index.php"]["8"]="W";
$PERM["pub"]["5"]="T_8";
$PERM["upload"]["5"]="T_8";
$PERM["online"]["*"]="R";
?>