<?
$PERM["admin"]["9"]="R";
$PERM["admin"]["7"]="R";
$PERM["admin"]["8"]="W";
$PERM["admin"]["*"]="D";
$PERM["rk.php"]["2"]="D";
$PERM["rk.php"]["6"]="D";
$PERM["rk.php"]["3"]="D";
$PERM["rk.php"]["4"]="D";
$PERM["rk.php"]["9"]="D";
$PERM["rk.php"]["7"]="X";
$PERM["rk.php"]["5"]="D";
$PERM["rk.php"]["8"]="D";
$PERM["rk.php"]["*"]="D";
$PERM["tools"]["5"]="T_8";
$PERM["wizards"]["*"]="D";
?><?
$PERM["fileman_html_editor_action.php"]["9"]="R";
?>